### ISSUE TITLE
Links in Environments readme file is broken

### ISSUE THREAD

**Issue by tomron** [google/ml-fairness-gym#8]
Links in [Environments readme](https://github.com/google/ml-fairness-gym/blob/master/environments/README.md) are broken, for example, link to College Admission - https://github.com/google/ml-fairness-gym/blob/master/examples/docs/college_admission_example.md (no such file in the repository)

**Comment by hansa0** [comment]
Thanks for raising this issue, the readme links across the repo should be all working now!
