### ISSUE TITLE
Error While running attention_allocation_experiment in acm_fat_2020

### ISSUE THREAD

**Issue by amuhebwa** [google/ml-fairness-gym#9]
While the other two experiments run, i keep getting this error concerned with Multi processing pool. 
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x114b00f10>'. Reason: 'PicklingError("Can't pickle <class 'TypeError'>: it's not the same object as builtins.TypeError")'

**Comment by hansa0** [comment]
Thanks for raising this issue - it should now be fixed in the current version of the code.
